---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-penid-client-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: openid-client-secret

  data:
    - secretKey: clientSecret
      remoteRef:
        key: OAUTH_CLIENT_SECRET