apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
