apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # RBAC
  - rbac/grp-sigaint-admins.yaml

  # Console
  - console/logo.yaml
  - console/cluster.yaml

  # API Server
  - apiserver/api-certificate-tls.yaml
  - apiserver/cluster.yaml

  # Ingress
  - ingress/ingress-default-tls.yaml
  - ingress/default.yaml

  # Oauth
  - authentication/oidc-secret.yaml
  - authentication/oauth.yaml
