---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traccar
  namespace: sigaint-traccar
spec:
  interval: 5m
  chart:
    spec:
      chart: traccar
      sourceRef:
        kind: HelmRepository
        name: sigaint-traccar
        namespace: sigaint-traccar
      interval: 1m
  values:
    image:
      flavor: "alpine"
    externalService:
      type: ClusterIP
      enabled: true
    securityContext:
    podSecurityContext:
    traccar:
      securityContext:
      podSecurityContext:
      ingress:
        enabled: true
        extraAnnotations: {}
        annotations: {}
        hosts:
          - host: traccar.apps.sigaint.au
            paths:
              - /
        tls: []
    mysql:
      auth:
        database: "traccar"
        username: "traccar"
        password: "traccar"
      primary:
        enabled: true
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          enabled: true
      secondary:
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          enabled: true
