---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 5m
  chart:
    spec:
      chart: paperless-ngx
      version: '2.4.3'
      sourceRef:
        kind: HelmRepository
        name: paperless-ngx
        namespace: paperless-ngx
      interval: 1m
  values:
    postgresql: true
