apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/ceph-csi.yaml
  - resources/ceph.yaml
  - resources/repository.yaml
  - resources/release.yaml
