apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-default
  namespace: openshift-ingress
spec:
  secretName: ingress-default-tls
  commonName: "*.apps.ocp.sigaint.au"
  dnsNames:
    - "*.apps.ocp.sigaint.au"
  issuerRef:
    name: le-production
    kind: ClusterIssuer