---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager-operator
  name: le-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: m4487@sigaint.au
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager-operator
  name: le-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-production-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: m4487@sigaint.au
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token