---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-cloudflare-api-token-secret
  namespace: cert-manager-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: cloudflare-api-token-secret

  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN