apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver
  namespace: openshift-config
spec:
  secretName: apiserver-tls
  commonName: "api.ocp.sigaint.au"
  dnsNames:
    - "api.ocp.sigaint.au"
  issuerRef:
    name: le-production
    kind: ClusterIssuer